### ISSUE TITLE
іменування

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/React-UserCard#10]
https://github.com/VasylUlianovskyi/React-UserCard/blob/32edf6b82d6b9960dfcf8dabc96b6bb5a5758fc9/src/LoginForm/LoginForm.jsx#L16
- тут використовується дієслово, за іменуванням десь нижче в коді можна сприйняти, що це функція. Краще намагатися без дієслів. Натомість можна використати віддієслівний іменник (вродьби це так називається 🙃):
```javascript
 const [passwordConfirmation, setPasswordConfirmation] = useState(""); 
``` 
або скоротити для більш короткої назви
```javascript
 const [passwConfirmation, setPasswConfirmation] = useState(""); 
``` 
--------------
https://github.com/VasylUlianovskyi/React-UserCard/blob/32edf6b82d6b9960dfcf8dabc96b6bb5a5758fc9/src/LoginForm/LoginForm.jsx#L17
- тут скоріше `isPasswordShown` або `isPasswordVisible` або `isPasswordHidden` (тільки тоді true і false будуть навпаки). Наступний стан аналогічно.
--------------
https://github.com/VasylUlianovskyi/React-UserCard/blob/32edf6b82d6b9960dfcf8dabc96b6bb5a5758fc9/src/LoginForm/LoginForm.jsx#L13
- краще зберігати регістр, краще сприйматиметься:
```javascript
 const [fullName, setFullName] = useState(""); 
``` 
або
```javascript
 const [fullname, setFullname] = useState(""); 
``` 
--------------
https://github.com/VasylUlianovskyi/React-UserCard/blob/32edf6b82d6b9960dfcf8dabc96b6bb5a5758fc9/src/LoginForm/LoginForm.jsx#L41
- тут функція, тому краще дієслово (або процес), наприклад, `changePasswordVisibility`
Тоді (+ ще іменування `isPasswordVisible`, хоча тут це і локальна змінна, а не стан), наприклад, функція обчислення іконки ока буде набагато краще читатися:
```javascript
  const passwordIcon = (type, isPasswordVisible) =>
    isPasswordVisible ? (
      <FaRegEyeSlash
        className={styles.regEyeBtn}
        onClick={() => changePasswordVisibility(type)}
      />
    ) : (
      <FaRegEye
        className={styles.regEyeBtn}
        onClick={() => changePasswordVisibility(type)}
      />
    );
```

**Comment by VasylUlianovskyi** [comment]
++

**Comment by pecourses** [comment]
https://github.com/VasylUlianovskyi/React-UserCard/blob/a74ace61c28c4cd9f5d4fa41da5cf05e38de301f/src/LoginForm/LoginForm.jsx#L18
- це теж логічне значення, а з назви цього не зрозуміло, за назвою це ніби якась функція
