### ISSUE TITLE
fullscreen bug

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/React-UserCard#11]
https://github.com/VasylUlianovskyi/React-UserCard/blob/a74ace61c28c4cd9f5d4fa41da5cf05e38de301f/src/Slider/index.jsx#L56
- зараз на фулскрін (стан) інші стилі, але проблема в тому, що  фулскрін режим і фулстрін стан не винхронізовано. Фулскрін стан змінюється при натисканні на відповідну кнопку на слайдері, фулскрін режим - вхід - на цю ж кнопку, тому ці речі синхронізовано. Вихід з режиму - та ж кнопка АБО _вбудовані можливості браузера_, а вихід зі стану - тільки кнопка. Треба якось відстідежувати, якщо використали _вбудовані можливості браузера_ і тоді теж скидати фулскрін. Наприклад, взагалі перекласти відповідальність за зміну стану фулскріну на зміну режиму фулскріну:
```javascript
  useEffect(() => {
    const fullscreenchangeHandler = () => setIsFullScreen(e => !e);

    document.addEventListener("fullscreenchange", fullscreenchangeHandler);

    return () => {
      document.removeEventListener("fullscreenchange", fullscreenchangeHandler);
    };
  }, []);

  const handleFullScreenChange = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch(err => {
        console.error("Error attempting to enter full-screen mode:", err);
      });
    } else {
      document.exitFullscreen().catch(err => {
        console.error("Error attempting to exit full-screen mode:", err);
      });
    }
    // setIsFullScreen(e => !e);
  };
```

**Comment by VasylUlianovskyi** [comment]
++
