### ISSUE TITLE
валідаційна схема

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/React-UserCard#12]
https://github.com/VasylUlianovskyi/React-UserCard/blob/76486d88a84c11eb94251a03d257e325bdfc82ae/utils/validationSchemas.js#L15
- якщо до схеми додати умови на радіо та чекбокс
```javascript
  term: yup.boolean().oneOf([true]).required(),
  type: yup.string().oneOf(["buyer", "creative"]).required(),
``` 
то форма не буде сабмітитися, поки користувач не погодиться з умовами та не обере роль

**Comment by VasylUlianovskyi** [comment]
++
