### ISSUE TITLE
рефакторинг

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/React-UserCard#2]
https://github.com/VasylUlianovskyi/React-UserCard/blob/3273abf5e697625bd85530f6f7bfab0f158c5510/src/UserCard/index.jsx#L80-L85
- щоб розмітка краще читалася, подібні обчислення зручно виносити з розмітки, наприклад, так:
```javascript
  const followedBtnIcon = followed ?
    <i className="fa-solid fa-check"></i>
    :
    <i className="fa-solid fa-plus"></i>
``` 
тоді в розмітці використаємо цю змінну
```javascript
      <button className={style.followBtn} onClick={handleFollow}>
        {followedBtnIcon}
      </button>
```

**Comment by VasylUlianovskyi** [comment]
++
