### ISSUE TITLE
імпорт стилів

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/React-UserCard#3]
https://github.com/VasylUlianovskyi/React-UserCard/blob/32edf6b82d6b9960dfcf8dabc96b6bb5a5758fc9/index.html#L16
- в цій збірці стилі доєднуються до компонентів (специфічні для компонента, зроблені як модулі стилів) або головного main.jsx (якщо загальні стилі), тут не потрібно їх доєднувати. Загалом, весь код знаходитиметься в `src`, за винятком окремих статичних файлів, зокрема якихось загальних зображень, які будуть в `public`. Відповідно, ми і не будемо сильно змінювати файли поза межами `src`, тому тут в індексі доречні, наприклад, якісь посилання на зовнішні ресурси (як fontawesome), але не на код. З кодом в `src` індекс пов'язує лише `<script type="module" src="/src/main.jsx"></script>`, а всі файли всередині src перетворюються на остаточний код бандлером (зборщиком) і вже ним доєднуються до індекса.

**Comment by VasylUlianovskyi** [comment]
Це залишилось в з попередньої домашки, в мене викилка тоді проблема з застосуванням стилів до рутового елеманта, проблему вирішів, це  забрати забув)
Вже виправив
