### ISSUE TITLE
шлях до файла

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/React-UserCard#4]
https://github.com/VasylUlianovskyi/React-UserCard/blob/32edf6b82d6b9960dfcf8dabc96b6bb5a5758fc9/src/UserList/UserList.jsx#L3
https://github.com/VasylUlianovskyi/React-UserCard/blob/32edf6b82d6b9960dfcf8dabc96b6bb5a5758fc9/src/UserList/UserListItem.jsx#L2
- нам нема сенсу виходити і входити в ту ж саму папку:
```javascript
import styles from "./UserList.module.css";
```

**Comment by VasylUlianovskyi** [comment]
++
