### ISSUE TITLE
key

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/React-UserCard#6]
https://github.com/VasylUlianovskyi/React-UserCard/blob/32edf6b82d6b9960dfcf8dabc96b6bb5a5758fc9/src/UserList/UserList.jsx#L69
- ключем має бути `id` для уникнення багів (значення, унікальне саме для конкретного елемента, а індекс, якщо видаляти/додавати/сортувати елементи, буде змінюватися). Зараз ця особливість не проявилася, але може наздогнати в неочікуваний момент)

**Comment by VasylUlianovskyi** [comment]
++
