### ISSUE TITLE
порядок імпортів

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/React-UserCard#9]
https://github.com/VasylUlianovskyi/React-UserCard/blob/32edf6b82d6b9960dfcf8dabc96b6bb5a5758fc9/src/LoginForm/LoginForm.jsx#L1-L5
- порядок імпортів ([докладніше](https://github.com/VasylUlianovskyi/React-UserCard/issues/8))

**Comment by VasylUlianovskyi** [comment]
++
